<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Faketorio.Sim\Faketorio.Sim.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="ModelContextProtocol" Version="2.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\data\**" CopyToOutputDirectory="PreserveNewest" LinkBase="data" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Faketorio.Sim.McpServer.Tests" />
  </ItemGroup>

</Project>
